### Crear un producto
POST http://localhost:5094/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 1200.00,
  "stock": 10
}

### Crear una orden
POST http://localhost:5094/api/orders
Content-Type: application/json

{
  "1": 2
}

### Consultar órdenes
GET http://localhost:5094/api/orders